[package]
name = "wgpu-biolerless"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "0.13.1"
bytemuck = { version = "1.11.0", features = ["derive"] }
parking_lot = "0.12.1"
anyhow = "1.0.60"
raw-window-handle = "0.4.3"
